export const SET_NEW_COORDINATES = 'SET_NEW_COORDINATES';
export const SET_NEW_ADDRESS = 'SET_NEW_ADDRESS';
export const SELECTED_ADDRESS = 'SELECTED_ADDRESS';
export const SET_TEMPERATURE = 'SET_TEMPERATURE';
export const LOADED_DATA = 'LOADED_DATA';